# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Build Site
        run: make

      - name: Upload artifacts
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: site
          FOLDER: playground/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
